services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: finControl_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: kt#syw3@Bj

    ports:
      - "5432:5432"
    volumes:
      - /pgdata:/var/lib/postgresql/data
